name: aurum_proxy
description: Aurum Proxy - black-gold VPN/proxy client for Android and iOS.
publish_to: "none"
version: 1.0.3+103

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  shared_preferences: ^2.3.3
  mobile_scanner: ^6.0.2
  v2ray_box:
    path: third_party/v2box

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
